name: flutter_coffee_ui
description: flutter_coffee_ui

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_icons_null_safety: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: varela
      fonts:
        - asset: assets/VarelaRound-Regular.ttf
    - family: nunito
      fonts:
        - asset: assets/Nunito-Regular.ttf
        - asset: assets/Nunito-Light.ttf
          weight: 300